name: "PlayerFundUnlockables"
main: "sh.reece.playerfundunlockable.Main"
version: "1.0.0"
api-version: "1.16"
author: "Reecepbcups"
depend: ["Vault"]
commands:
  fund:
    aliases: [funds]
    description: "Main command to deposit funds to the area for a player"